---
- name: Load AWS YAML file
  include_vars:
    file: "{{ vars.aws_config_file }}"
    name: aws_data

- name: Copy private ssh key
  vars:
    ssh_key: "{{ aws_data.sshKey }}"
    ssh_file: "{{ ssh_key.split('/')[-1] }}"
  ansible.builtin.copy:
    src: "{{ aws_data.sshKey }}"
    dest: /home/{{ ansible_user }}/.ssh/{{ ssh_file }}
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'